# This is a basic workflow to help you get started with Actions

name: CI

on:
  push:
    branches: 
      - main
  schedule:
    - cron: '0 0 * * 1'

jobs:
  daily_check_in:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: 'Set up Python'
        uses: actions/setup-python@v1
        with:
          python-version: 3.7
      - name: 'Install requirements'
        run: pip install -r ./requirements.txt

        
        
        
      - name: 'Working'
        env:
          MAIL_USER: ${{ secrets.MAIL_USER }}
          MAIL_PASS: ${{ secrets.MAIL_PASS }}
          SEND_MAIL: ${{ secrets.SEND_MAIL }}
          RECEIVE_MAIL: ${{ secrets.RECEIVE_MAIL }}
        run: python send_email_pubmed_papers.py




